### ISSUE TITLE
test data

### ISSUE THREAD

**Issue by zhangxiangxuan** [2496772010/cesium-s3m-parser-demo#1]
If the test data is not classified, could you give me a copy of the test data?

**Comment by 2496772010** [comment]
不好意思，数据是公司的，不能随便传输的

**Comment by zhangxiangxuan** [comment]
请问supermap-iserver里面的/samples/data/REalspasce/CBD/Building@CBD这份数据格式是不是不对的，是得自己用OSGB格式的数据重新转一份S3M吗

**Comment by 2496772010** [comment]
是的

**Comment by zhangxiangxuan** [comment]
已经加载出来了，感谢感谢

**Comment by 2496772010** [comment]
好的
